[package]
name = "oozextract"
description = "Open source Kraken / Mermaid / Selkie / Leviathan / LZNA / Bitknit decompressor"
repository = "https://github.com/lvlvllvlvllvlvl/oozextract"
version = "0.4.0"
edition = "2021"
license = "MIT"
exclude = ["testdata", "verify"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = "1.19.0"
bytes = "1.8.0"
clap = { version = "4.5.20", optional = true, features = ["derive"] }
futures = "0.3.31"
log = "0.4.22"
test-log = "0.2.16"
tokio = { version = "1.41.0", optional = true, features = ["io-util"] }
wasm-bindgen = { version = "0.2.95", optional = true }
wide = "0.7.28"

[dev-dependencies]
criterion = "0.5.1"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["io"] }

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false
[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ['-O4', '-g']
[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']

[[bench]]
name = "criterion"
harness = false

[features]
x86_sse = []
async = []
tokio = ["async", "dep:tokio"]
wasm = ["dep:wasm-bindgen"]
verbose_errors = []
cli = ["dep:clap"]
