name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cargo install cargo-all-features wasm-pack
          cargo build-all-features
          wasm-pack build --target web --features wasm
          npx -y wasm-pack-inline pkg --dir pkg/inline
      - name: Run tests
        run: cargo test --release --verbose --features tokio
